"""
Rule-based reward model for the Redrob candidate-ranking RL task.

We deliberately do NOT use an LLM-as-a-judge. Instead we score model outputs
with a deterministic, transparent rubric so:

    * training is fully reproducible
    * rewards are cheap (CPU-only, sub-millisecond per sample)
    * the reward signal is auditable - every component can be inspected

The model is asked to return a short JSON object of the form::

    {
      "decision": "shortlist" | "reject",
      "score": <float 0..1>,
      "reasons": ["bullet 1", "bullet 2", ...]
    }

The reward is a weighted sum of small rule-based components, each in [0, 1].

Components
----------
1. ``format_valid``       - parses as JSON with the required keys      (0/1)
2. ``decision_match``     - decision matches the gold label            (0/1)
3. ``score_alignment``    - 1 - |pred_score - gold_score|              ([0,1])
4. ``reason_quality``     - >=2 short reasons, no copy-paste of input  ([0,1])
5. ``length_penalty``     - completion within sensible token budget    ([0,1])
6. ``no_hallucination``   - reasons reference only words that appear   ([0,1])
                            in the candidate / JD context

The final reward is in [0, 1] and is the convex combination of the components
using the weights declared on the dataclass.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional, Tuple


# --------------------------------------------------------------------------- #
# Public dataclasses
# --------------------------------------------------------------------------- #

@dataclass
class RewardBreakdown:
    """Per-sample breakdown of every reward component (for plots / debugging)."""

    format_valid: float = 0.0
    decision_match: float = 0.0
    score_alignment: float = 0.0
    reason_quality: float = 0.0
    length_penalty: float = 0.0
    no_hallucination: float = 0.0
    total: float = 0.0

    def as_dict(self) -> Dict[str, float]:
        return asdict(self)


# --------------------------------------------------------------------------- #
# Reward model
# --------------------------------------------------------------------------- #

@dataclass
class RuleBasedRewardModel:
    """
    Deterministic, rule-based reward function for GRPO.

    Weights default to a balanced mix; tune via the constructor.
    """

    w_format: float = 0.20
    w_decision: float = 0.30
    w_score: float = 0.15
    w_reason: float = 0.15
    w_length: float = 0.05
    w_hallucination: float = 0.15

    min_reasons: int = 2
    max_reasons: int = 5
    max_completion_chars: int = 1200
    min_completion_chars: int = 30

    # ----- public API ------------------------------------------------------ #

    def __call__(
        self,
        completion: str,
        *,
        gold_decision: str,
        gold_score: float,
        context_text: str,
    ) -> Tuple[float, RewardBreakdown]:
        """
        Compute the scalar reward and breakdown for one completion.

        Parameters
        ----------
        completion : str
            The raw text generated by the policy.
        gold_decision : str
            Ground-truth label: ``"shortlist"`` or ``"reject"``.
        gold_score : float
            Ground-truth score in [0, 1].
        context_text : str
            The candidate + JD text that was shown in the prompt. Used to
            detect blatant hallucinations in the reasons.
        """
        bd = RewardBreakdown()

        # 1) format validity
        parsed = self._safe_parse_json(completion)
        bd.format_valid = 1.0 if parsed is not None else 0.0

        # 2) decision match
        pred_decision = (parsed.get("decision") if parsed else "") or ""
        pred_decision = pred_decision.strip().lower()
        bd.decision_match = 1.0 if pred_decision == gold_decision else 0.0

        # 3) score alignment
        pred_score = self._safe_float(parsed.get("score") if parsed else None)
        if pred_score is None:
            bd.score_alignment = 0.0
        else:
            pred_score = max(0.0, min(1.0, pred_score))
            bd.score_alignment = 1.0 - abs(pred_score - gold_score)

        # 4) reason quality
        reasons = parsed.get("reasons") if parsed else None
        bd.reason_quality = self._reason_quality(reasons, context_text)

        # 5) length penalty
        bd.length_penalty = self._length_penalty(completion)

        # 6) hallucination check (no fabricated proper nouns / numbers)
        bd.no_hallucination = self._no_hallucination(reasons, context_text)

        # weighted sum
        total = (
            self.w_format * bd.format_valid
            + self.w_decision * bd.decision_match
            + self.w_score * bd.score_alignment
            + self.w_reason * bd.reason_quality
            + self.w_length * bd.length_penalty
            + self.w_hallucination * bd.no_hallucination
        )
        # normalise so the max is exactly 1.0 even if weights don't sum to 1
        total = total / max(
            self.w_format + self.w_decision + self.w_score
            + self.w_reason + self.w_length + self.w_hallucination,
            1e-9,
        )
        bd.total = float(total)
        return float(total), bd

    # ----- helpers --------------------------------------------------------- #

    _JSON_OBJ_RE = re.compile(r"\{[\s\S]*\}")

    @classmethod
    def _safe_parse_json(cls, text: str) -> Optional[Dict[str, Any]]:
        """Find the first ``{...}`` block in ``text`` and try to parse it."""
        if not text:
            return None
        m = cls._JSON_OBJ_RE.search(text)
        if not m:
            return None
        blob = m.group(0)
        for candidate in (blob, blob.replace("'", '"')):
            try:
                obj = json.loads(candidate)
                if isinstance(obj, dict):
                    return obj
            except Exception:
                continue
        return None

    @staticmethod
    def _safe_float(x: Any) -> Optional[float]:
        try:
            return float(x)  # type: ignore[arg-type]
        except Exception:
            return None

    def _reason_quality(
        self, reasons: Any, context_text: str
    ) -> float:
        if not isinstance(reasons, list) or not reasons:
            return 0.0
        clean = [
            r.strip() for r in reasons
            if isinstance(r, str) and 3 <= len(r.strip()) <= 240
        ]
        if not clean:
            return 0.0
        count_score = min(len(clean), self.max_reasons) / self.max_reasons
        if len(clean) < self.min_reasons:
            count_score *= 0.5
        # diversity: ratio of unique tokens across reasons
        toks: List[str] = []
        for r in clean:
            toks.extend(re.findall(r"[a-zA-Z][a-zA-Z\-]{2,}", r.lower()))
        diversity = (len(set(toks)) / max(len(toks), 1)) if toks else 0.0
        # not just copy-pasted from context
        ctx_lower = context_text.lower()
        copy_ratio = sum(
            1 for r in clean if r.lower() in ctx_lower
        ) / len(clean)
        anti_copy = 1.0 - copy_ratio
        return float(0.5 * count_score + 0.3 * diversity + 0.2 * anti_copy)

    def _length_penalty(self, completion: str) -> float:
        n = len(completion or "")
        if n < self.min_completion_chars:
            return n / max(self.min_completion_chars, 1)
        if n <= self.max_completion_chars:
            return 1.0
        # linear decay past the cap, floor at 0
        over = n - self.max_completion_chars
        return max(0.0, 1.0 - over / self.max_completion_chars)

    @staticmethod
    def _no_hallucination(reasons: Any, context_text: str) -> float:
        """
        Reward grounded reasons. We extract numeric tokens (e.g. "8 years",
        "10001+") and capitalised proper nouns from the reasons and check
        that each appears verbatim in the context. Penalty is proportional
        to the fraction that are NOT grounded.
        """
        if not isinstance(reasons, list) or not reasons:
            return 0.0
        text_blob = " ".join([r for r in reasons if isinstance(r, str)])
        candidates: List[str] = []
        candidates += re.findall(r"\b\d+(?:\.\d+)?\b", text_blob)
        candidates += re.findall(
            r"\b[A-Z][a-zA-Z0-9\-]{2,}(?:\s+[A-Z][a-zA-Z0-9\-]{2,})*\b",
            text_blob,
        )
        if not candidates:
            return 1.0  # nothing risky claimed -> safe
        ctx = context_text or ""
        grounded = sum(1 for c in candidates if c in ctx)
        return float(grounded / len(candidates))


# --------------------------------------------------------------------------- #
# TRL adapter
# --------------------------------------------------------------------------- #

def make_trl_reward_fn(
    reward_model: RuleBasedRewardModel,
    *,
    gold_decisions: List[str],
    gold_scores: List[float],
    contexts: List[str],
):
    """
    Build a TRL-compatible ``reward_funcs`` callable.

    TRL's ``GRPOTrainer`` passes ``prompts`` and ``completions`` plus any
    extra dataset columns as keyword arguments. We accept the gold labels
    via the ``decision`` / ``score`` / ``context`` columns of the dataset.
    """

    def _reward_fn(completions, **kwargs) -> List[float]:
        # ``completions`` is a list of strings (one per prompt-group sample)
        decisions = kwargs.get("decision") or gold_decisions
        scores = kwargs.get("score") or gold_scores
        ctxs = kwargs.get("context") or contexts

        out: List[float] = []
        for i, comp in enumerate(completions):
            gd = decisions[i] if i < len(decisions) else decisions[0]
            gs = scores[i] if i < len(scores) else scores[0]
            cx = ctxs[i] if i < len(ctxs) else ctxs[0]
            r, _bd = reward_model(
                comp,
                gold_decision=gd,
                gold_score=float(gs),
                context_text=cx,
            )
            out.append(r)
        return out

    _reward_fn.__name__ = "rule_based_reward"
    return _reward_fn
